version: '3.1'

services:

  goAdmindb:
    image: mysql:5.6
    # DB型別為utf8mb4 ...
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci', --default-authentication-plugin=mysql_native_password]
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: qwe1234
      MYSQL_DATABASE: GoAdmin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
